
# Тема 10. Декораторы и исключения
Отчет по Теме #10 выполнил(а):
- Поляков Матвей Андреевич
- ИВТ-22-2

| Задание | Лаб_раб | Сам_раб |
| ------ | ------ | ------ |
| Задание 1 | + | + |
| Задание 2 | + | + |
| Задание 3 | + | + |
| Задание 4 | + | + |
| Задание 5 | + | + |
| Задание 6 | - | - |
| Задание 7 | - | - |
| Задание 8 | - | - |
| Задание 9 | - | - |
| Задание 10 | - | - |

знак "+" - задание выполнено; знак "-" - задание не выполнено;

Работу проверили:
- к.э.н., доцент Панов М.А.

  ## Лабораторная №1
  ### Наверняка вы думаете, что декораторы – это какая-то бесполезная вещь, которая вам никогда не пригодится, но тут вдруг на паре по математике преподаватель просит всех посчитать число Фибоначчи для 100. Кто-то будет считать вручную (так точно не нужно), кто-то посчитает на калькуляторе, а кто-то подумает, что он самый крутой и напишет рекурсивную программу на Python и немного огорчится, потому что данная программа будет достаточно долго считаться, если ее просто так запускать. Но именно тут к вам на помощь приходят декораторы, например @lru_cache (он предназначен для решения задач динамическим программированием, если простыми словами, то этот декоратор запоминает промежуточные результаты и при рекурсивном вызове функции программа не будет считать одни и те же значения, а просто “возьмёт их из этого декоратора”). Вам нужно написать программу, которая будет считать числа Фибоначчи для 100 и запустить ее без этого декоратора и с ним, посмотреть на разницу во времени решения поставленной задачи. P.S. при запуске без декоратора можете долго не ждать, для наглядности хватит 10 секунд ожидания.
  ```python
    from functools import lru_cache
    
    
    @lru_cache(None) #декоратор
    def get_sum(n):
        if n == 0:
            return 0
        elif n == 1:
            return 1
        return get_sum(n - 1) + get_sum(n-2)
    
    if __name__ == "__main__":
        print(get_sum(100))
  ```
  # Результат
![Меню](https://github.com/soft2k/Software_Engineering/blob/Tema10/pic/Screenshot_1.png)
  # Вывод
  Код вычисляет сумму последовательности Фибоначчи для числа 100 с использованием кэширования результатов промежуточных вычислений, что значительно ускоряет работу рекурсивной функции.


   ## Лабораторная №2
  ### Илья пишет свой сайт и ему необходимо сделать минимальную проверку ввода данных пользователя при регистрации. Для этого он реализовал функцию, которая выводит данные пользователя на экран и решил, что будет проверять правильность введённых данных при помощи декоратора, но в этом ему потребовалась ваша помощь. Напишите декоратор для функции, который будет принимать все параметры вызываемой функции (имя, возраст) и проверять чтобы возраст был больше 0 и меньше 130. Причем заметьте, что неважно сколько пользователь введет данных на сайт к Илье, будут обрабатываться только первые 2 аргумента.
  
  ```python
    def check(input_func):
      def output_func(*args):
        name, age = args[0], args[1]
    
        if age < 0 or age > 130:
          age = 'Недопустимый возраст'
        input_func(name, age)
    
      return output_func
    
      
    @check 
    def personal_info(name, age):
      print(f"Имя: {name}, Возраст: {age}")
    
    
    if __name__ == '__main__':
      personal_info('Матвей', 20)
      personal_info('Никита', -19)
      personal_info('Екатерина', 140,50,1)
  ```
  # Результат
![Меню](https://github.com/soft2k/Software_Engineering/blob/Tema10/pic/Screenshot_2.png)
  # Вывод
  Код демонстрирует использование декоратора для валидации входных данных функции personal_info, который проверяет корректность возраста (от 0 до 130 лет) и выводит информацию о человеке, заменяя некорректный возраст на строку 'Недопустимый возраст'.



   ## Лабораторная №3
  ### Вам понравилась идея Ильи с сайтом, и вы решили дальше работать вместе с ним. Но вот в вашем проекте появилась проблема, кто-то пытается сломать вашу функцию с получением данных для сайта. Эта функция работает только с данными integer, а какой-то недохакер пытается все сломать и вместо нужного типа данных отправляет string. Воспользуйтесь исключениями, чтобы неподходящий тип данных не ломал ваш сайт. Также дополнительно можете обернуть весь код функции в try/except/finally для того, чтобы программа вас оповестила о том, что выявлена какая-то ошибка или программа успешно выполнена.
  
  ```python
      def data(*args):
        try: 
          for i in range(len(args[0])):
            try:
              result = (args[0][i] * 15) // 10
              print(result)
            except Exception as ex:
              print(ex)
        except Exception as ex:
          print(ex)
        finally:
          print('Всё обработано')
      
      
      data([1, 15, 'Hello', 'i', 'try', 'too','crash','your','site',38,35])
  ```
  # Результат
![Меню](https://github.com/soft2k/Software_Engineering/blob/Tema10/pic/Screenshot_3.png)
  # Вывод
  С помощью print вывели 3 строки - обычная строка, строка с -f и использование переменной в print и сложили две переменные в print



   ## Лабораторная №4
  
  ### Продолжая работу над сайтом, вы решили написать собственное исключение, которое будет вызываться в случае, если в функцию проверки имени при регистрации передана строка длиннее десяти символов, а если имя имеет допустимую длину, то в консоль выводиться “Успешная регистрация”
  ```python
      class NegativeValueException(Exception):
        pass
      
      
      def check_name(name):
        if len(name) > 10:
          raise NegativeValueException('Длина более 10 символов')
        else:
          print('Успешная регестрация')
      
      if __name__ == '__main__':
          check_name('239193193')
          print("-"*40)
          check_name('239193193149')
  ```
  # Результат
![Меню](https://github.com/soft2k/Software_Engineering/blob/Tema10/pic/Screenshot_4.png)
  # Вывод
  
Код определяет пользовательское исключение NegativeValueException и функцию check_name, которая проверяет длину строки имени; если длина превышает 10 символов, выбрасывается исключение, иначе выводится сообщение об успешной регистрации, при этом при вызове функции с именем длиной 12 символов будет сгенерировано исключение.
  


## Лабораторная №5
  
  ### После запуска сайта вы поняли, что вам необходимо добавить логгер, для отслеживания его работы. Готовыми вариантами вы не захотели пользоваться, и поэтому решили создать очень простую пародию. Для этого создали две функции: init() (вызывается при создании класса декоратора в программе) и call() (вызывается при вызове декоратора). Создайте необходимый вам декоратор. Выведите все логи в консоль.
  ```python
    class SiteChecker:
      def __init__(self, func):
        print('> Класс SiteChecker метод __init__ запущен')
        self.func = func
    
      
      def __call__(self):
        print('> Проверка', self.func.__name__)
        self.func()
        print('> Проверка')
    
    
    @SiteChecker
    def site():
      print('Работа сайта')
    
    
    print('>> Сайт запущен')
    site()
    print('>> Сайт выключен')
  ```
  # Результат
![Меню](https://github.com/soft2k/Software_Engineering/blob/Tema10/pic/Screenshot_5.png)
  # Вывод
 Код демонстрирует использование декоратора-класса SiteChecker, который при вызове функции site() добавляет дополнительные действия до и после её выполнения: выводит информацию о проверке в консоль, что позволяет реализовать простой механизм обёртки с расширенным логированием.



  ## Самостоятельная работа №1
  ### Вовочка решил заняться спортивным программированием на python, но для этого он должен знать за какое время выполняется его программа. Он решил, что для этого ему идеально подойдет декоратор для функции, который будет выяснять за какое время выполняется та или иная функция. Помогите Вовочке в его начинаниях и напишите такой декоратор. Подсказка: необходимо использовать модуль time Декоратор необходимо использовать для этой функции:
  ```python
        import time
        
        def time_decorator(func):
            def wrapper(*args, **kwargs):
                start_time = time.time() 
                result = func(*args, **kwargs)  
                end_time = time.time() 
                execution_time = end_time - start_time  
                print(f"Время выполнения функции '{func.__name__}': {execution_time:.6f} секунд")
                return result
            return wrapper
        
        @time_decorator
        def fibonacci():
            fib1 = fib2 = 1
            for i in range(2, 200):
                fib1, fib2 = fib2, fib1 + fib2
                print(fib2, end=' ')
            print()
        
        if __name__ == '__main__':
            fibonacci()
  ```
  # Результат
![Меню](https://github.com/soft2k/Software_Engineering/blob/Tema10/pic/Screenshot_6.png)
  # Вывод

  Декоратор time_decorator измеряет время выполнения функции fibonacci(), которая генерирует последовательность чисел Фибоначчи, и выводит затраченное время с точностью до микросекунд.


   ## Самостоятельная работа №2
  ### Посмотрев на Вовочку, вы также загорелись идеей спортивного программирования, начав тренировки вы узнали, что для решения некоторых задач необходимо считывать данные из файлов. Но через некоторое время вы столкнулись с проблемой что файлы бывают пустыми, и вы не получаете вводные данные для решения задачи. После этого вы решили не просто считывать данные из файла, а всю конструкцию оборачивать в исключения, чтобы избежать такой проблемы. Создайте пустой файл и файл, в котором есть какая-то информация. Напишите код программы. Если файл пустой, то, нужно вызвать исключение (“бросить исключение”) и вывести в консоль “файл пустой”, а если он не пустой, то вывести информацию из файла.
  
  ```python

      with open('empty_file.txt', 'w') as f:
          pass  
      
      with open('filled_file.txt', 'w') as f:
          f.write('Это файл с некоторой информацией.\n')
      
      
      def read_file(file_name):
          try:
              with open(file_name, 'r') as f:
                  content = f.read()
                  if not content: 
                      raise ValueError("файл пустой")
                  print(content)  
          except ValueError as e:
              print(e) 
          except FileNotFoundError:
              print("Файл не найден")  
          except Exception as e:
              print(f"Произошла ошибка: {e}")  
      
      
      if __name__ == '__main__':
          print("Чтение из пустого файла:")
          read_file('empty_file.txt')  
      
          print("\nЧтение из файла с содержимым:")
          read_file('filled_file.txt') 
  ```
  # Результат
![Меню](https://github.com/soft2k/Software_Engineering/blob/Tema10/pic/Screenshot_7.png)
  # Вывод
 Программа считывает содержимое файлов, используя механизм исключений для обработки ситуации с пустыми файлами, выбрасывая специальное исключение и выводя сообщение "файл пустой", если файл не содержит данных.



   ## Самостоятельная работа №3
  ### Напишите функцию, которая будет складывать 2 и введенное пользователем число, но если пользователь введет строку или другой неподходящий тип данных, то в консоль выведется ошибка “Неподходящий тип данных. Ожидалось число.”. Реализовать функционал программы необходимо через try/except и подобрать правильный тип исключения. Создавать собственное исключение нельзя. Проведите несколько тестов, в которых исключение вызывается и нет. Результатом выполнения задачи будет листинг кода и получившийся вывод в консоль
  
  ```python
      def add_two_and_number():
          try:
              user_input = input("Введите число: ")  
              number = float(user_input)  
              result = 2 + number 
              print(f"Результат: {result}")  
          except ValueError:
              print("Неподходящий тип данных. Ожидалось число.") 
      
      # Тестирование функции
      if __name__ == '__main__':
          add_two_and_number()  
          add_two_and_number()
          add_two_and_number() 
  ```
  # Результат
![Меню](https://github.com/soft2k/Software_Engineering/blob/Tema10/pic/Screenshot_8.png)
  # Вывод
Функция пытается преобразовать пользовательский ввод в число с помощью float(), складывает его с 2 и выводит результат, а в случае возникновения ошибки преобразования (например, при вводе строки) перехватывает исключение ValueError и выводит сообщение "Неподходящий тип данных. Ожидалось число."



   ## Самостоятельная работа №4
  
  ### Создайте собственный декоратор, который будет использоваться для двух любых вами придуманных функций. Декораторы, которые использовались ранее в работе нельзя воссоздавать. Результатом выполнения задачи будет: класс декоратора, две как-то связанными с ним функциями, скриншот консоли с выполненной программой и подробные комментарии, которые будут описывать работу вашего кода.
  ```python
class LoggerDecorator:
    def __call__(self, func):
        def wrapper(*args):
            print(f"Вызов функции {func.__name__} с аргументами {args}")
            result = func(*args)
            print(f"Результат: {result}")
            return result
        return wrapper

@LoggerDecorator()
def greet(name):
    return f"Привет, {name}!"

@LoggerDecorator()
def add(a, b):
    return a + b

def main():
    greet("Матвей")
    add(5, 3)

if __name__ == "__main__":
    main()
  ```
  # Результат

![Меню](https://github.com/soft2k/Software_Engineering/blob/Tema10/pic/Screenshot_9.png)
  # Вывод
 
  Декоратор LoggerDecorator создает обертку для функций, которая автоматически выводит информацию о вызове функции, ее аргументах и результате, не изменяя основной логики исходной функции.


   ## Самостоятельная работа №5
  
  ### Создайте три переменные: день (тип данных - числовой), месяц (тип данных - строка), год (тип данных - числовой) и выведите в консоль текущую дату в формате: “Сегодня день месяц год. Всего хорошего!” используя F строку и оператор end внутри print(), в котором вы должны написать фразу “Всего хорошего!”. Программа должна занимать не более двух строк редактора кода

  ```python
      class CustomValueError(Exception):
          pass
      
      def validate_positive_number(value):
          if value < 0:
              raise CustomValueError(f"Значение должно быть положительным: {value}")
      
      def process_value(value):
      
          validate_positive_number(value)
          print(f"Обрабатываем значение: {value}")
      
      def main():
          try:
              process_value(-10)  # Пример с отрицательным числом
          except CustomValueError as e:
              print(f"Ошибка: {e}")
      
          try:
              process_value(5)  # Пример с положительным числом
          except CustomValueError as e:
              print(f"Ошибка: {e}")
      
      if __name__ == "__main__":
          main()
  ```
  # Результат
![Меню](https://github.com/soft2k/Software_Engineering/blob/Tema10/pic/Screenshot_10.png)
  # Вывод
  Код создает пользовательское исключение CustomValueError для проверки положительных чисел, которое используется в двух сценариях: при попытке обработать отрицательное число (вызывает ошибку) и при обработке положительного числа (выполняется успешно).



  

   
  
  


  

  






